# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_auto_20170314_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='qqr', max_length=200),
        ),
    ]
