# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
