# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0008_auto_20170314_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='choice_filled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='choice',
            field=models.IntegerField(default=-1),
        ),
    ]
